hipache:
    image: tutum/hipache:0.3.1
    ports:
        - "80:80"
    links:
        - redis:redis
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

redis:
    image: redis:3.0.1
    command: redis-server --appendonly yes
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

mysql:
    image: mysql:5.7.4
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=cloudunit
    ports:
        - 3306:3306
    volumes_from:
        - mysqldata
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

mysqldata:
    image: ubuntu:14.04
    volumes:
        - /var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

dnsdock:
    image: tonistiigi/dnsdock:v1.10.0
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
       - "172.17.42.1:53:53/udp"
    command: -nameserver="8.8.8.8:53" -http=":80" -dns=":53" -verbose="true" -environment="cloud" -domain="unit"

tomcat:
    image: tomcat:7-jre8
    volumes:
        - ./tomcat:/usr/local/tomcat/webapps
        - ./certificats:/usr/local/tomcat/certificats
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - /var/log/cloudunit/tomcat/culogin.log:/var/log/culogin.log
        - /home/admincu/.cloudunit:/root/.cloudunit
    environment:
        - CU_SUB_DOMAIN
        - CU_KVM
        - CATALINA_OPTS="-Dspring.profiles.active=production"
        - MYSQL_ROOT_PASSWORD

cadvisor:
    image: google/cadvisor:0.14.0
    environment:
        - DB_USER=root
        - DB_PASS=root
        - DB_NAME=cadvisor
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    command: --housekeeping_interval=5s

nginx:
    image: nginx:1.9.0
    ports:
        - "443:443"
    links:
        - tomcat:tomcat
    volumes:
        - ./nginx/sites-enabled:/etc/nginx/sites-enabled
        - ./nginx/cloudunit.io:/etc/ssl/cloudunit.io
        - ./nginx/log:/var/log/nginx
        - ./nginx/www:/var/www
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro