version: '2'
services:

  testmysql:
      container_name: cuplatform_testmysql_1
      image: mysql:5.7.4
      depends_on:
           - mysqldata
      ports:
           - "3307:3306"
      environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_DATABASE=cloudunit
      volumes_from:
           - testmysqldata
      volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
      network_mode: bridge

  testmysqldata:
      container_name: cuplatform_testmysqldata_1
      image: ubuntu:14.04
      volumes:
          - /home/admincu/testmysql_home:/var/lib/mysql
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      network_mode: bridge
